package za.ac.cput.service;

import za.ac.cput.domain.*;
import za.ac.cput.enums.*;
import za.ac.cput.repository.SaleRepository;
import za.ac.cput.repository.CarRepository;
import za.ac.cput.repository.EmployeeRepository;


import com.itextpdf.text.*;
import com.itextpdf.text.pdf.*;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;


import java.io.ByteArrayOutputStream;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

@Service
@RequiredArgsConstructor
public class PdfService {

    private final SaleRepository saleRepository;
    private final CarRepository carRepository;
    private final EmployeeRepository employeeRepository;

    //PDF styling constants
    private static final Font TITLE_FONT =
            new Font(Font.FontFamily.HELVETICA, 18, Font.BOLD, BaseColor.WHITE);
    private static final Font HEADER_FONT =
            new Font(Font.FontFamily.HELVETICA, 11, Font.BOLD, BaseColor.WHITE);
    private static final Font BODY_FONT =
            new Font(Font.FontFamily.HELVETICA, 10, Font.NORMAL, BaseColor.BLACK);
    private static final Font LABEL_FONT =
            new Font(Font.FontFamily.HELVETICA, 10, Font.BOLD, BaseColor.BLACK);
    private static final BaseColor BRAND_COLOR = new BaseColor(30, 30, 90);
    private static final BaseColor ROW_ALT = new BaseColor(230, 235, 245);

    // Helper methods for PDF generation

    private void addTitleBar(Document doc, String title) throws DocumentException {
        PdfPTable titleTable = new PdfPTable(1);
        titleTable.setWidthPercentage(100);
        PdfPCell cell = new PdfPCell(new Phrase(title, TITLE_FONT));
        cell.setBackgroundColor(BRAND_COLOR);
        cell.setPadding(12);
        cell.setBorder(Rectangle.NO_BORDER);
        titleTable.addCell(cell);
        doc.add(titleTable);
        doc.add(Chunk.NEWLINE);
    }

    private PdfPCell headerCell(String text) {
        PdfPCell cell = new PdfPCell(new Phrase(text, HEADER_FONT));
        cell.setBackgroundColor(BRAND_COLOR);
        cell.setPadding(7);
        cell.setBorder(Rectangle.NO_BORDER);
        return cell;
    }

    private PdfPCell bodyCell(String text, boolean alternate) {
        PdfPCell cell = new PdfPCell(new Phrase(text, BODY_FONT));
        cell.setBackgroundColor(alternate ? ROW_ALT : BaseColor.WHITE);
        cell.setPadding(6);
        cell.setBorder(Rectangle.NO_BORDER);
        return cell;
    }

    private void addFooter(Document doc) throws DocumentException {
        doc.add(Chunk.NEWLINE);
        Paragraph footer = new Paragraph(
                "Generated by Buzz Car Sales System", 
                new Font(Font.FontFamily.HELVETICA, 8, Font.ITALIC, BaseColor.GRAY));
        footer.setAlignment(Element.ALIGN_RIGHT);
        doc.add(footer);
    }

    // Sale Report: Lists all sales with details, grouped by employee and branch, with totals

    public byte[] generateSalesReport() throws DocumentException {
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        Document doc = new Document(PageSize.A4.rotate());
        PdfWriter.getInstance(doc, out);
        doc.open();

        addTitleBar(doc, "Buzz Car Sales — Sales Report");

        
        List<Sale> sales = saleRepository.findAll();
        double total = sales.stream().mapToDouble(Sale::getSalePrice).sum();

        Paragraph summary = new Paragraph();
        summary.add(new Chunk("Total Sales: ", LABEL_FONT));
        summary.add(new Chunk(String.valueOf(sales.size()), BODY_FONT));
        summary.add(new Chunk("     Total Revenue: ", LABEL_FONT));
        summary.add(new Chunk("R" + String.format("%,.2f", total), BODY_FONT));
        doc.add(summary);
        doc.add(Chunk.NEWLINE);

        PdfPTable table = new PdfPTable(7);
        table.setWidthPercentage(100);
        table.setWidths(new float[]{1f, 2f, 2f, 2.5f, 2f, 1.5f, 1.5f});

        table.addCell(headerCell("Sale ID"));
        table.addCell(headerCell("Customer"));
        table.addCell(headerCell("Car"));
        table.addCell(headerCell("VIN"));
        table.addCell(headerCell("Employee"));
        table.addCell(headerCell("Date"));
        table.addCell(headerCell("Price (R)"));

        DateTimeFormatter fmt = DateTimeFormatter.ofPattern("dd MMM yyyy");
        boolean alt = false;
        for (Sale s : sales) {
            String customer = s.getCustomer().getFirstName() + " " + s.getCustomer().getLastName();
            String car = s.getCar().getCarModel().getCarMake().getMakeName() + " "
                    + s.getCar().getCarModel().getModelName();
            String employee = s.getEmployee().getFirstName() + " " + s.getEmployee().getLastName();
            String date = s.getSaleDate().format(fmt);
            String price = String.format("%,.2f", s.getSalePrice());

            table.addCell(bodyCell(String.valueOf(s.getSaleId()), alt));
            table.addCell(bodyCell(customer, alt));
            table.addCell(bodyCell(car, alt));
            table.addCell(bodyCell(employee, alt));
            table.addCell(bodyCell(date, alt));
            table.addCell(bodyCell(price, alt));
            alt = !alt;
        }

        doc.add(table);
        addFooter(doc);
        doc.close();
        return out.toByteArray();
    }

    // Available Cars Report: Lists all available cars with details, grouped by branch
    public byte[] generateAvailableCarsReport() throws DocumentException {
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        Document doc = new Document(PageSize.A4.rotate());
        PdfWriter.getInstance(doc, out);
        doc.open();

        addTitleBar(doc, "Buzz Car Sales — Available Cars Report");

        List<Car> cars = carRepository.findByStatus(Status.AVAILABLE);

        Paragraph summary = new Paragraph();
        summary.add(new Chunk("Total Available Cars: ", LABEL_FONT));
        summary.add(new Chunk(String.valueOf(cars.size()), BODY_FONT));
        doc.add(summary);
        doc.add(Chunk.NEWLINE);

        
        Map<String, List<Car>> byBranch = cars.stream()
                .collect(Collectors.groupingBy(c -> c.getBranch().getBranchName()));

        for (Map.Entry<String, List<Car>> entry : byBranch.entrySet()) {
            
            Paragraph branchHeading = new Paragraph(
                    "Branch: " + entry.getKey(), LABEL_FONT);
            branchHeading.setSpacingBefore(10);
            doc.add(branchHeading);

            PdfPTable table = new PdfPTable(6);
            table.setWidthPercentage(100);
            table.setWidths(new float[]{1f, 2f, 2f, 1.5f, 1.5f, 1.5f});

            table.addCell(headerCell("Car ID"));
            table.addCell(headerCell("Make & Model"));
            table.addCell(headerCell("VIN"));
            table.addCell(headerCell("Condition"));
            table.addCell(headerCell("Year"));
            table.addCell(headerCell("Price (R)"));

            boolean alt = false;
            for (Car c : entry.getValue()) {
                String makeModel = c.getCarModel().getCarMake().getMakeName()
                        + " " + c.getCarModel().getModelName();
                table.addCell(bodyCell(String.valueOf(c.getCarId()), alt));
                table.addCell(bodyCell(makeModel, alt));
                table.addCell(bodyCell(c.getCondition().name(), alt));
                table.addCell(bodyCell(String.valueOf(c.getYear()), alt));
                table.addCell(bodyCell(String.format("%,.2f", c.getPrice()), alt));
                alt = !alt;
            }

            doc.add(table);
            doc.add(Chunk.NEWLINE);
        }

        addFooter(doc);
        doc.close();
        return out.toByteArray();
    }

    // Employee Sales Performance Report: Shows sales performance metrics for each employee
    public byte[] generateEmployeePerformanceReport() throws DocumentException {
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        Document doc = new Document(PageSize.A4.rotate());
        PdfWriter.getInstance(doc, out);
        doc.open();

        addTitleBar(doc, "Buzz Car Sales — Employee Sales Performance Report");

        List<Sale> allSales = saleRepository.findAll();

        Map<Integer, List<Sale>> byEmployee = allSales.stream()
                .collect(Collectors.groupingBy(s -> s.getEmployee().getEmployeeId()));

        PdfPTable table = new PdfPTable(6);
        table.setWidthPercentage(100);
        table.setWidths(new float[]{1f, 2.5f, 2f, 1.5f, 2f, 2f});

        table.addCell(headerCell("Emp ID"));
        table.addCell(headerCell("Employee Name"));
        table.addCell(headerCell("Branch"));
        table.addCell(headerCell("Total Sales"));
        table.addCell(headerCell("Total Revenue (R)"));
        table.addCell(headerCell("Job Title"));

        boolean alt = false;
        for (Map.Entry<Integer, List<Sale>> entry : byEmployee.entrySet()) {
            List<Sale> empSales = entry.getValue();
            Employee emp = empSales.get(0).getEmployee();
            String name = emp.getFirstName() + " " + emp.getLastName();
            String branch = emp.getBranch().getBranchName();
            String totalSales = String.valueOf(empSales.size());
            String totalRevenue = String.format("%,.2f",
                    empSales.stream().mapToDouble(Sale::getSalePrice).sum());
            String jobTitle = emp.getJobTitle().name();

            table.addCell(bodyCell(String.valueOf(emp.getEmployeeId()), alt));
            table.addCell(bodyCell(name, alt));
            table.addCell(bodyCell(branch, alt));
            table.addCell(bodyCell(totalSales, alt));
            table.addCell(bodyCell(totalRevenue, alt));
            table.addCell(bodyCell(jobTitle, alt));
            alt = !alt;
        }

        doc.add(table);
        addFooter(doc);
        doc.close();
        return out.toByteArray();
    }
}